### ISSUE TITLE
Can't build on Debian Bullseye

### ISSUE THREAD

**Issue by shgubar** [ClearPathDigital/easyedit-debian#1]
Hi
Please help with this issue. I can't build. Get error:
```
/bin/ld: new_curse.o:(.bss+0x0): multiple definition of `top_of_win'; ee.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [make.local:12: ee] Error 1
```
I tried other versions of ncurses but same error.
Thanks for any help.

**Comment by ClearPathDigital** [comment]
@shgubar, please try checking out the static-top_of_win branch and let me know if it solves your build issue.

**Comment by shgubar** [comment]
Yes, this is solved my issue build.
Maked and installed.
Thank you very much.
